In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("NIA notebook is working!")

Pandas version: 3.0.5
NIA notebook is working!

In [2]:
import pandas as pd

DATA_PATH = "../data/raw/archive/twcs/twcs.csv"

df = pd.read_csv(DATA_PATH, nrows=10)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Shape: (10, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 10 non-null     int64
 1   author_id                10 non-null     str
 2   inbound                  10 non-null     bool
 3   created_at               10 non-null     str
 4   text                     10 non-null     str
 5   response_tweet_id        8 non-null      str
 6   in_response_to_tweet_id  9 non-null      float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 622.0 bytes

In [4]:
df["inbound"].value_counts()

inbound
False    5
True     5
Name: count, dtype: int64

In [5]:
df[["inbound", "text"]]

   inbound                                               text
0    False  @115712 I understand. I would like to assist y...
1     True      @sprintcare and how do you propose we do that
2     True  @sprintcare I have sent several private messag...
3    False  @115712 Please send us a Private Message so th...
4     True                                 @sprintcare I did.
5    False  @115712 Can you please send us a private messa...
6     True          @sprintcare is the worst customer service
7    False  @115713 This is saddening to hear. Please shoo...
8     True  @sprintcare You gonna magically change your co...
9    False  @115713 We understand your concerns and we'd l...